# Generated by Django 5.2.5 on 2025-08-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_quote_quote_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='weight',
            field=models.IntegerField(choices=[(1, 'low'), (2, 'medium'), (3, 'high')], default=2),
        ),
    ]
