# Generated by Django 5.2.5 on 2025-08-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='source',
            field=models.TextField(null=True),
        ),
    ]
