# Generated by Django 5.2.5 on 2025-08-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.TextField(),
        ),
    ]
